// <auto-generated />
using System;
using BillingDesk.Common;
using BillingDesk.Subscription.Types.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BillingDesk.Migrations
{
    [DbContext(typeof(BillingDeskDbContext))]
    [Migration("20260626182902_AddSubscriptionModel")]
    partial class AddSubscriptionModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("api")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "api", "billing_cycle", new[] { "monthly", "yearly" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "api", "currency", new[] { "eur", "mwk", "usd" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "api", "subscription_status", new[] { "active", "inactive" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BillingDesk.Subscription.Types.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<BillingCycle>("BillingCycle")
                        .HasColumnType("api.billing_cycle")
                        .HasColumnName("billing_cycle");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<Currency>("Currency")
                        .HasColumnType("api.currency")
                        .HasColumnName("currency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<LocalDate>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<SubscriptionStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("api.subscription_status")
                        .HasDefaultValue(SubscriptionStatus.Active)
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_subscription");

                    b.ToTable("subscription", "api");
                });
#pragma warning restore 612, 618
        }
    }
}
